In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/sunnysavita10/Naive-Bayes/main/SpamClassifier-with-ML/sms_spam_data/SMSSpamCollection.csv", sep='\t',header= None,names=['label','message'])

In [3]:
df

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
import nltk
import re

In [5]:
df.head(2)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...

In [6]:
df.shape

(5572, 2)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [8]:
df.describe()

label                 message
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [9]:
df.groupby(['label']).count()

message
label         
ham       4825
spam       747

In [10]:
df['label'].unique()

array(['ham', 'spam'], dtype=object)

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Ketandeep
[nltk_data]     Sharma\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
from nltk.corpus import stopwords

In [13]:
from nltk.stem.porter import PorterStemmer

In [14]:
ps=PorterStemmer()

In [28]:

l=[]

PREPROCESSING

In [29]:
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]',' ',df['message'][i])
    review=review.lower()
    review=review.split()
    
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    l.append(review)
    
    

In [31]:
l[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [32]:
l[40]

'pl go ahead watt want sure great weekend abiola'

# convert it in to a vector

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
cv=CountVectorizer(max_features=3000)

In [41]:
num=cv.fit_transform(l).toarray()
num[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
num.shape

(5572, 3000)

In [43]:
df['label']

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

Encoding label column

In [45]:
pd.get_dummies(df['label'])

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [47]:
y=pd.get_dummies(df['label'],drop_first=True)
y

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
x_train,x_test,y_train,y_test=train_test_split(num,y,test_size=0.25,random_state=10)

# Gaussian Based Model

In [51]:
from sklearn.naive_bayes import GaussianNB

In [52]:
gnb=GaussianNB()

In [53]:
gnb.fit(x_train,y_train)

c:\users\ketandeep sharma\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [55]:
y_pred=gnb.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1], dtype=uint8)

# Accuracy

In [56]:
from sklearn.metrics import accuracy_score 

In [58]:
accuracy_score(y_test,y_pred)*100

87.00646087580762

# Multinomial Naive Bayes

In [59]:
from sklearn.naive_bayes import MultinomialNB

In [60]:
mnb=MultinomialNB()

In [61]:
mnb.fit(x_train,y_train)

c:\users\ketandeep sharma\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [64]:
y_pred2=mnb.predict(x_test)
y_pred2

array([0, 0, 0, ..., 0, 0, 1], dtype=uint8)

Accuracy

In [65]:
accuracy_score(y_test,y_pred2)*100

97.4156496769562

# Final Observation
# So it is better to go with Multinomial naive bayes